### ISSUE TITLE
The Monero Ecosystem project is closing

### ISSUE THREAD

**Issue by erciccione** [Lafudoci/XMR-ETA#2]
Hi @Lafudoci. Please see https://github.com/monero-ecosystem/meta/issues/78#issuecomment-1891695536 and let me know how you plan to proceed forward.

**Comment by Lafudoci** [comment]
I'll move it back to my account in the following holidays, thanks.

**Comment by Lafudoci** [comment]
This repo has been transfer to my account. Closing issue.
